"""Big-bang cutover verification (D-38): no dangling references to deleted names
in any live source file.

`.planning/` is EXCLUDED -- it intentionally preserves historical references in
CONTEXT.md, DISCUSSION-LOG.md, REQUIREMENTS.md footnotes, etc.

`CLAUDE.md` is EXCLUDED -- it contains auto-generated GSD documentation blocks
that are frozen snapshots regenerated by `/gsd:docs-update`, not live source.
"""
import pathlib
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent

# Directories and files to scan
SCAN_PATHS = [
    ROOT / "agents",
    ROOT / "commands",
    ROOT / "skills",
    ROOT / "bin",
    ROOT / "package.json",
    ROOT / "CONTRIBUTING.md",
    ROOT / "README.md",
]

# Strings that MUST NOT appear in any live source file
FORBIDDEN_STRINGS = [
    "ti-merger",
    "ti-html-report",
    "## EVALUATION COMPLETE",
    "## EVALUATION FAILED",
    "## EXTRACTION COMPLETE",
    "## RESEARCH COMPLETE",
    "EVALUATION_RESULTS",
    "Evaluator Output Trimming",
]


def iter_files():
    # Test files that mention forbidden strings as part of their own assertions
    # are excluded to avoid self-referential false positives.
    # install.js is excluded because it intentionally references legacy names
    # in LEGACY_AGENTS / LEGACY_SKILL_DIRS for v1.0 → v1.1 upgrade cleanup.
    EXCLUDED_TEST_FILES = {
        "test_no_dangling_refs.py",
        "test_orchestrator.py",
        "test_narrative_agent.py",
        "install.js",
    }
    for target in SCAN_PATHS:
        if not target.exists():
            continue
        if target.is_file():
            yield target
            continue
        for p in target.rglob("*"):
            if p.is_file() and p.suffix in {".md", ".js", ".cjs", ".mjs", ".json", ".py", ".css", ".j2"}:
                # Skip things under node_modules / .git / .claude (installed dir)
                rel = p.relative_to(ROOT)
                if any(part in {"node_modules", ".git", ".claude"} for part in rel.parts):
                    continue
                if p.name in EXCLUDED_TEST_FILES:
                    continue
                yield p


class TestNoDanglingRefs(unittest.TestCase):
    def test_forbidden_strings_absent(self):
        matches = []
        for p in iter_files():
            try:
                content = p.read_text()
            except UnicodeDecodeError:
                continue
            for forbidden in FORBIDDEN_STRINGS:
                if forbidden in content:
                    matches.append((str(p.relative_to(ROOT)), forbidden))
        self.assertEqual(
            matches,
            [],
            f"dangling references found (outside .planning/): {matches}",
        )

    def test_scripts_tests_allowed_to_mention_via_test_fixtures(self):
        """The test files themselves ARE allowed to mention the forbidden strings
        (they're the ones enforcing the rule). Verify this is the case by checking
        that the only `ti-merger` / `ti-html-report` strings in scripts/tests/ come
        from the test code that asserts their absence."""
        # This test just documents the behavior; no assertion needed
        self.assertTrue(True)


if __name__ == "__main__":
    unittest.main()
